import {
  Accessibility,
  Activity,
  Bike,
  CircleDot,
  Dumbbell,
  Flag,
  Flame,
  Footprints,
  type LucideIcon,
  Mountain,
  MountainSnow,
  PersonStanding,
  Sailboat,
  Snowflake,
  Waves,
  Wind,
  Zap,
} from 'lucide-react';

export const ACTIVITY_TYPE_ICONS: Record<string, LucideIcon> = {
  AlpineSki: Mountain,
  BackcountrySki: MountainSnow,
  Canoeing: Sailboat,
  Crossfit: Dumbbell,
  EBikeRide: Zap,
  Elliptical: Activity,
  Golf: Flag,
  Handcycle: Bike,
  Hike: Footprints,
  IceSkate: Snowflake,
  InlineSkate: CircleDot,
  Kayaking: Sailboat,
  Kitesurf: Wind,
  NordicSki: MountainSnow,
  Ride: Bike,
  RockClimbing: Mountain,
  RollerSki: MountainSnow,
  Rowing: Sailboat,
  Run: Footprints,
  Sail: Sailboat,
  Skateboard: CircleDot,
  Snowboard: MountainSnow,
  Snowshoe: Footprints,
  Soccer: CircleDot,
  StairStepper: Activity,
  StandUpPaddling: Sailboat,
  Surfing: Waves,
  Swim: Waves,
  Velomobile: Bike,
  Walk: Footprints,
  WeightTraining: Dumbbell,
  Wheelchair: Accessibility,
  Windsurf: Wind,
  Workout: Flame,
  Yoga: PersonStanding,
};
